name: tutor_flutter
description: RegistroAnimalMX - Tutor App (Flutter PWA + Firebase)
publish_to: "none"

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  firebase_core: ^3.4.0
  firebase_auth: ^5.2.0
  cloud_firestore: ^5.4.2
  firebase_storage: ^12.2.0
  firebase_messaging: ^15.1.0
  firebase_analytics: ^11.3.0
  url_launcher: ^6.3.0
  go_router: ^14.2.0
  flutter_local_notifications: ^17.2.3
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
